### ISSUE TITLE
Error when creating a 96-well layout

### ISSUE THREAD

**Issue by emanuelsc87** [soorajachar/plateypus#1]
I get the following error when trying to create a simple layout for a 96-well plate

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/experimentSetupGUI.py", line 253, in <lambda>
    tk.Button(buttonWindow, text="OK",command=lambda: collectInputs()).grid(row=5,column=0)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/experimentSetupGUI.py", line 248, in collectInputs
    master.switch_frame(allLevelNamePage,folderName)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/__main__.py", line 26, in switch_frame
    new_frame = frame_class(self,*args)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/experimentSetupGUI.py", line 421, in __init__
    mainWindow = Frame(self)
NameError: name 'Frame' is not defined

![image](https://user-images.githubusercontent.com/52220284/117868920-28748580-b268-11eb-9381-8b7f53de39c7.png)

**Comment by soorajachar** [comment]
Good catch; should be fixed in 0.1.14
