### ISSUE TITLE
Error when selecting 'Create experiment layout'

### ISSUE THREAD

**Issue by emanuelsc87** [soorajachar/plateypus#2]
The following error appears when selecting 'Create experiment layout' and clicking 'OK':

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/experimentSetupGUI.py", line 96, in <lambda>
    tk.Button(buttonWindow, text="OK",command=lambda: collectInput()).grid(row=5,column=0)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/experimentSetupGUI.py", line 91, in collectInput
    experimentLayout()
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/experimentSetupGUI.py", line 63, in experimentLayout
    master.switch_frame(BlankSelectionPage,folderName,levels,levelValues,maxNumLevelValues,experimentParameters['numPlates'],plateDimensions,v3.get(),ExperimentSetupStartPage,bPage)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/__main__.py", line 30, in switch_frame
    new_frame = frame_class(self,*args)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 197, in __init__
    modifyPlatePlot()
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 179, in modifyPlatePlot
    fig_ax1.set_xticks([], [])
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
TypeError: set_ticks() takes 2 positional arguments but 3 were given

![image](https://user-images.githubusercontent.com/52220284/117890218-c2492c00-b282-11eb-8e56-2c0aeed53739.png)

**Comment by soorajachar** [comment]
Was due to deprecated matplotlib keyword; fixed in 0.1.15
