### ISSUE TITLE
Minor bug: openpyxl is not installed automatically with plateypus installation

### ISSUE THREAD

**Issue by emanuelsc87** [soorajachar/plateypus#4]
Just reporting this for other users that don't have much experience with command line.
Problem easily solved by doing pip install openpyxl

![image](https://user-images.githubusercontent.com/52220284/118130734-b7e67980-b3cb-11eb-9b0c-3011cc206f86.png)

/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/initialDataProcessing.py:295: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if 'Blank' in tempLevelValues:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 57, in <lambda>
    cellDfButton = tk.Button(mainWindow,text='Create dataframe',command=lambda: createDataFrame('cell'))
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 46, in createDataFrame
    dataProcessingMaster(folderName,expNum,dataType,ex_data,v3.get())
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 126, in dataProcessingMaster
    idp.saveFinalDataFrames(folderName,secondPath,expNum,dataType,celldf,ex_data)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/initialDataProcessing.py", line 329, in saveFinalDataFrames
    convertDataFramesToExcel(folderName,secondPath,dataType,fullExperimentDf)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/initialDataProcessing.py", line 312, in convertDataFramesToExcel
    writer = pd.ExcelWriter('outputData/excelFiles/excelFile-'+folderName+'-'+dataType+'.xlsx')
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/pandas/io/excel/_openpyxl.py", line 30, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'

**Comment by soorajachar** [comment]
Fixed in plateypus 0.1.17; openpyxl and tables (for hdf5 file saving), which are optional pandas dependencies, have been added to required plateypus dependencies
