### ISSUE TITLE
Minor bug: Cytokine layout is created but Cell layout is not

### ISSUE THREAD

**Issue by emanuelsc87** [soorajachar/plateypus#5]
To solve this problem, I just copied the "cyt" layout pkl file and renamed it for "cell". 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 57, in <lambda>
    cellDfButton = tk.Button(mainWindow,text='Create dataframe',command=lambda: createDataFrame('cell'))
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 46, in createDataFrame
    dataProcessingMaster(folderName,expNum,dataType,ex_data,v3.get())
  File "/Users/salazarcavazoe2/anaconda3/envs/py38/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 111, in dataProcessingMaster
experimentLevelLayoutDict = pickle.load(open('misc/layoutDict-'+folderName+'-'+parameterExtension+'.pkl','rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'misc/layoutDict-20210513-B16_OVA_Q4_NaiveOT1_w_wo_IL_7_Exp1-cell.pkl'

**Comment by soorajachar** [comment]
Fixed in plateypus 0.1.17
