### ISSUE TITLE
Use of characters in layout: not OK?

### ISSUE THREAD

**Issue by Immunodynamics** [soorajachar/plateypus#6]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 980, in <lambda>
    tk.Button(selectionWindow, text="Deselect Wells",command=lambda: selectWells(False,advanceVar.get())).grid(row=0,column=0)
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 763, in selectWells
    updatePlatePlot(changedInbox,0)
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 535, in updatePlatePlot
    fig_ax1.legend_.remove()
AttributeError: 'NoneType' object has no attribute 'remove'
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/mathtext.py", line 2617, in parse
    result = self._expression.parseString(s)
  File "/opt/anaconda3/lib/python3.8/site-packages/pyparsing.py", line 1955, in parseString
    raise exc
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/mathtext.py", line 2775, in unknown_symbol
    raise ParseFatalException(s, loc, "Unknown symbol: %s" % c)
pyparsing.ParseFatalException: Unknown symbol: \, found '\'  (at char 6), (line:1, col:7)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 1021, in <lambda>
    self.FinishButton = tk.Button(buttonWindow, text="Finish",command=lambda: collectInputs(),font='Helvetica 14 bold')
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 969, in collectInputs
    createLayoutVisual(baseLayoutDf,finalLayoutDict['keys'][i],i,level,levelValues,plateDimensions,numRowPlates,numColumnPlates,dt,infoDf,vlinelist,hlinelist)
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/setup/createPlateLayout.py", line 422, in createLayoutVisual
    plt.savefig('plots/plateLayouts/plateLayout-'+currentLevel+'-'+dt+'.png',bbox_inches='tight')
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2193, in print_figure
    self.figure.draw(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/figure.py", line 1863, in draw
    mimage._draw_list_compositing_images(
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2747, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/legend.py", line 606, in draw
    bbox = self._legend_box.get_window_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 346, in get_window_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 471, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 471, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 544, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 544, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 471, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 471, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 341, in get_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 544, in get_extent_offsets
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 544, in <listcomp>
    whd_list = [c.get_extent(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/offsetbox.py", line 886, in get_extent
    bbox, info, d = self._text._get_layout(renderer)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/text.py", line 293, in _get_layout
    w, h, d = renderer.get_text_width_height_descent(
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 233, in get_text_width_height_descent
    self.mathtext_parser.parse(s, self.dpi, prop)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/mathtext.py", line 3340, in parse
    return self._parse_cached(
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/mathtext.py", line 3364, in _parse_cached
    box = self._parser.parse(s, font_output, fontsize, dpi)
  File "/opt/anaconda3/lib/python3.8/site-packages/matplotlib/mathtext.py", line 2619, in parse
    raise ValueError("\n".join(["",
ValueError: 
\bfRIG\-I construct
      ^
Unknown symbol: \, found '\'  (at char 6), (line:1, col:7)

**Comment by soorajachar** [comment]
What characters did you use exactly that threw the error? Was it fixed when you switched back to alphanumeric characters?

**Comment by Immunodynamics** [comment]
The name of the construct was:
RIG-I [K58A]
I believe the – was not to Plateypus’s taste

From: soorajachar ***@***.***>
Reply-To: soorajachar/plateypus ***@***.***>
Date: Wednesday, May 19, 2021 at 5:06 AM
To: soorajachar/plateypus ***@***.***>
Cc: "Immunodynamics Group, NCI" ***@***.***>, Author ***@***.***>
Subject: Re: [soorajachar/plateypus] Use of characters in layout: not OK? (#6)


What characters did you use exactly that threw the error? Was it fixed when you switched back to alphanumeric characters?

**Comment by soorajachar** [comment]
Yeah I fixed the hyphen issue but not the brackets; I'll look into that now

**Comment by soorajachar** [comment]
Fixed in plateypus 0.1.18
