### ISSUE TITLE
Processing cell data

### ISSUE THREAD

**Issue by Immunodynamics** [soorajachar/plateypus#7]
Did not create the layout for bulk cell measurements:

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 57, in <lambda>
    cellDfButton = tk.Button(mainWindow,text='Create dataframe',command=lambda: createDataFrame('cell'))
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 46, in createDataFrame
    dataProcessingMaster(folderName,expNum,dataType,ex_data,v3.get())
  File "/opt/anaconda3/lib/python3.8/site-packages/plateypus/dataprocessing/dataProcessingGUI.py", line 111, in dataProcessingMaster
    experimentLevelLayoutDict = pickle.load(open('misc/layoutDict-'+folderName+'-'+parameterExtension+'.pkl','rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'misc/layoutDict-20210518-RIGI_mutant_HLA-cell.pkl'

**Comment by soorajachar** [comment]
Fixed in 0.1.20
